### PR TITLE
Fix for https://github.com/OVAL-Community/OVAL/issues/79

### PR DESCRIPTION
**Pull request by solind**

### CODE REVIEW

**Comment by solind** [comment]
Consensus call...

**Comment by zport** [comment]
Hi David,

Looks like the consensus call was issued over 14 days ago... should we move this into develop?

Zack

**Comment by solind** [comment]
Yes, but last I checked I do not have authority to do so with my account.  So, please merge and close.

**Comment by zport** [comment]
Merged! Thanks @solind.

**Pull request merged**
