### PR TITLE
Deprecated 122 oval tests with no documented usage

### PR DESCRIPTION
**Pull request by vanderpol**
This pull request is pending additional feedback from OVAL consumers.  Will be decided and merged in after 11-07-2024

### CODE REVIEW

**Comment by vanderpol** [comment]
Please review the following file for cross referencing what should be deprecated:  https://github.com/user-attachments/files/17378654/OVAL_Test_Usage_in_Public_and_Private_Content_Oct_2024.xlsx

Also you can search through the XSD files for "This test has been deprecated due to lack of documented usage and will be removed in version 6.0 of the language." and you should find 122 instances.

**Comment by vanderpol** [comment]
Given our timeframe to complete both OVAL 5.12 and 6.0 by the end of the month, I'd like to merge this change into develop.  If you don't have time to do a review, just let me know and I'll just proceed with my personal review.

**Review by solind — COMMENTED** [review]
So, this all looks okay to me after a cursory review, but honestly I don't have the energy to verify all the deprecation entries against the spreadsheet (sorry).  The thing to do would be to write an XSLT (or maybe just an XPATH query) to pull out all the tests you're deprecating, and then you could compare the output to the expected results.

Didn't someone else volunteer to review this one?

**Comment by vanderpol** [comment]
@solind no worries, and a cursory review may suffice on this as long as the files are schema valid, the deprecation stuff is literally just documentation.  We'll know if I made any mistakes when I go to delete them all in OVAL 6.0.  We did have another volunteer, and I added them (or hopefully I added the right person) as a reviewer.

**Pull request merged**
