### PR TITLE
File Attribute Type

### PR DESCRIPTION
**Pull request by wmunyan**
Added allowable empty string enumeration value for Entity(State|Item)FileAttributeType, per standard for other OVAL enumeration types.

### CODE REVIEW

**Comment by solind** [comment]
Good catch.  Was there an issue associated with this?

**Comment by wmunyan** [comment]
@solind it was something we came across in our testing.  The OVAL results added an empty element with a status of "does not exist" and it failed schema validation.  Temporary workaround is to just not add the element to the `file_item`, since its a 0..unbounded, but wanted to keep consistency with other enums.

**Comment by isimluk** [comment]
LGTM.

**Comment by solind** [comment]
This is a good change because we need the state to be able to potentially accommodate a variable value.  However, I don't think it's actually possible for a Windows file to have no attributes, as in that case it should have FILE_ATTRIBUTE_NORMAL, which is defined as:

"A file that does not have other attributes set. This attribute is valid only when used alone."

**Comment by solind** [comment]
This also needs to be closed and changed into a pull request to merge into the develop branch.

**Pull request merged**
