### PR TITLE
Added several new sql dbms management systems to EntityObjectEngineType 

### PR DESCRIPTION
**Pull request by vanderpol**
Added several newer SQL DBMS engines for possible future use

### CODE REVIEW

**Review by solind — CHANGES_REQUESTED** [review]
You need to make corresponding changes to  the `EntityItemEngineType` in `independent-system-characteristics-schema.xsd`.

**Comment by vanderpol** [comment]
Thanks @solind for that catch.  I'm wondering if for OVAL 6.0 there's a way to prevent all of these duplicated enumerations that we tend to forget to update with time?  Feels like these enumerations need to be part of a 'common' file vs duplicated in definitions and system-chars.

Update is ready for your review.

**Review by solind — APPROVED** [review]

**Comment by solind** [comment]
> I'm wondering if for OVAL 6.0 there's a way to prevent all of these duplicated enumerations that we tend to forget to update with time? Feels like these enumerations need to be part of a 'common' file vs duplicated in definitions and system-chars.

I think it should be investigated as something we could do with schema consolidation.  First someone needs to research why/how it came to be the way it is now!

**Comment by vanderpol** [comment]
@solind, I think we'd have to talk to the original guys at MITRE who developed the spec to know (maybe Jon Baker or Danny Haynes?) Either way, we are where we are... I'll ponder the level of effort to improve it for 6.0, and see if we have time.

**Pull request merged**
