### PR TITLE
Merging develop branch (aka 5.12) into Master for official release

### PR DESCRIPTION
**Pull request by vanderpol**
OVAL 5.12 is ready for release

### CODE REVIEW

**Comment by vanderpol** [comment]
There is one conflict that is noteworthy IMHO on this, and it's the unix sshd test.  Given that the updates on the develop branch are 3 months newer than updates committed to the master, (and I'm not sure why anything was committed to the master), I'm leaning towards saying develop is 'correct', but I'd like a second opinion.

https://github.com/OVAL-Community/OVAL/pull/197/conflicts

@wmunyan do you have any backstory on this?  Was the commit to the master just accidental before we created a develop branch for pre-release updates of OVAL?

**Comment by solind** [comment]
> There is one conflict that is noteworthy IMHO on this, and it's the unix sshd test. Given that the updates on the develop branch are 3 months newer than updates committed to the master, (and I'm not sure why anything was committed to the master), I'm leaning towards saying develop is 'correct', but I'd like a second opinion.
> 
> https://github.com/OVAL-Community/OVAL/pull/197/conflicts
> 
> @wmunyan do you have any backstory on this? Was the commit to the master just accidental before we created a develop branch for pre-release updates of OVAL?

I'm not @wmunyan but I remember there was a desire to add a filepath to this test/object so that you could target a particular sshd_config file.

**Comment by vanderpol** [comment]
> > There is one conflict that is noteworthy IMHO on this, and it's the unix sshd test. Given that the updates on the develop branch are 3 months newer than updates committed to the master, (and I'm not sure why anything was committed to the master), I'm leaning towards saying develop is 'correct', but I'd like a second opinion.
> > https://github.com/OVAL-Community/OVAL/pull/197/conflicts
> > @wmunyan do you have any backstory on this? Was the commit to the master just accidental before we created a develop branch for pre-release updates of OVAL?
> 
> I'm not @wmunyan but I remember there was a desire to add a filepath to this test/object so that you could target a particular sshd_config file.

Thanks @solind, that lends more credibility to the updates of sshd on the develop branch vs master.   Unless I hear otherwise from @wmunyan, (or anyone else with other issues concerns), I'm hoping to complete this merge later today if possible, so we can get 5.12 done and clean up the master before we branch for 6.0 work.

**Comment by solind** [comment]
> @solind and others, I just realized that I mis-read the merge conflict in the linux schemas, there is a new LSMOD test in the master that isn't in develop branch. There is quite a bit of discussion on it with #74
> 
> Just want to makes sure that what is committed to master is ready for production use.
> 
> If my understanding of @wmunyan comment on #74, the LSMOD test was to be pulled, and not merged into master?

Oh, indeed, it looks like those were supposed to be replaced by a single kernelmodule_test.  They should not have been merged into master; that must have been a mistake!

**Comment by vanderpol** [comment]
> > @solind and others, I just realized that I mis-read the merge conflict in the linux schemas, there is a new LSMOD test in the master that isn't in develop branch. There is quite a bit of discussion on it with #74
> > Just want to makes sure that what is committed to master is ready for production use.
> > If my understanding of @wmunyan comment on #74, the LSMOD test was to be pulled, and not merged into master?
> 
> Oh, indeed, it looks like those were supposed to be replaced by a single kernelmodule_test. They should not have been merged into master; that must have been a mistake!

There were several commits to Master for Linux/UNIX defs it appears back in 2019, here's the primary commit that seems to be causing the current issues.  https://github.com/OVAL-Community/OVAL/commit/301c9ed2b9b0611f905f9ec908201c8439f63ebb

I'm currently planning to resolve the conflict, with the develop version being the 'correct' one for all instances.

**Comment by vanderpol** [comment]
OK, I've committed what I think resolves that conflict, with develop being current.  Definitely would like a sanity check on all of it though.  Thanks!

**Comment by vanderpol** [comment]
Proceeding with merging develop into master, I've personally reviewed it and it seems safe.  If we had more time, I'd wait for additional reviews.  But I need to move on to OVAL 6.0 efforts.

**Pull request merged**
