### PR TITLE
Proposal: Add new appcmd and appcmdlistconfig tests for checking IIS servers on Windows, and fix backward compatibility typo on EntityItemFileTypeType (take 2)

### PR DESCRIPTION
**Pull request by vanderpol**
Per oval team members, I'm redoing the updates from PR 109 based on the develop branch, not master, this should reduce the noise that was in the PR #109

This PR should resolve the issue in ticket #31 and add appcmd features per tickets #76 and #77

### CODE REVIEW

**Comment by vanderpol** [comment]
As I don't have permissions to request a review, @adammontville can you add @solind and @wmunyan as reviewers?

**Comment by solind** [comment]
Thanks for doing this, @vanderpol, cursorily it looks good; I'll try and do a full review this week.

**Comment by wmunyan** [comment]
@vanderpol The only thing I am seeing is that in the `appcmd_item` you have the datatypes for `parameter` and `result` backwards (you have `parameter` as an `oval-sc:EntityItemAnySimpleType`, and the `result` as an `oval-sc:EntityItemStringType`).

Other than that, it looks good to me!

**Comment by solind** [comment]
Hi @vanderpol, I diffed your proposed changes against the stand-alone version I created for prototyping, and I concur with @wmunyan that the entity types are flip-flopped for parameter and result (where < denotes your version from the PR and > denotes my version):

```
22c31
<    <xsd:element name="parameter" type="oval-sc:EntityItemAnySimpleType" minOccurs="0" maxOccurs="1">
---
>    <xsd:element name="parameter" type="oval-sc:EntityItemStringType" minOccurs="0" maxOccurs="1">
27c36
<    <xsd:element name="result" type="oval-sc:EntityItemStringType" minOccurs="0" maxOccurs="1">
---
>    <xsd:element name="result" type="oval-sc:EntityItemAnySimpleType" minOccurs="0" maxOccurs="1">
38c47
```
Other than that, it seems ready to go.

**Comment by vanderpol** [comment]
Thanks for catching this!  Dang copy/paste bug, and the fact that I can't use GitHub desktop on my work computer, so I can't easily diff what we have in our version control.    I also have notes (on my other computer) with regards to PR process which I'll share as well, it might show up temporarily as a note on this ticket.

**Comment by vanderpol** [comment]
Update committed which should resolve the copy/paste typos flip/flop identified by @wmunyan  and @solind.

**Comment by vanderpol** [comment]
@adammontville below are some very basic notes I took while creating a PR, and getting it to the point of being reviewed by others.  

OVAL schema update notes for github
1.  Download and install GitHub Desktop 
2.  Checkout the OVAL repository in Github Desktop
3.  Select the branch of 'origin/develop' (do not select master)
4.  Make your edits using your editor of choice
5.  Diff your changes
6.  Commit to your local branch, making a useful comments.
7.  Push to origin
8.  Create a pull request, name it:  "Proposal:  <whatever it is you want to add/fix>
9.  In PR conversation link any tickets (using #<ticket number>) that this PR is intended to resolve.  Example:  This fixes the issue reported in ticket #1 and adds a feature that does <blarg> per ticket #2 etc...
10. If it's ready for a peer review, request it from @adammontville

**Review by solind — APPROVED** [review]
Looks good.

**Pull request merged**
